### PR TITLE
Create pre-defined OrganizationRoleTemplates from kustomize configuration.

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:
Currently, we have two pre-defined OrganizationRoleTemplates for Organization Owners, which can be shared by all organizations in Bulward system. These 2 templates are created in Organization controller after the creation of the first Organization in the cluster: https://github.com/kubermatic/bulward/blob/master/pkg/manager/internal/controllers/organization_controller.go#L212-L228
This works, but it is not transparent to bulward system admin, and admin doesn't have a full control of these templates.

#42 provides a potential usage of bulward (as an operator library), so I think it makes more sense to include these pre-defined templates in the manifest, so they are more transparent to bulward admin, and they have full control (edit permission) of these templates and customize persmission privilege as they want.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jiachengxu** [comment]
@nmiculinic I have no idea why e2e test is complaining about
`unable to recognize "STDIN": no matches for kind "OrganizationRoleTemplate" in version "bulward.io/v1alpha1"`
since from the output of e2e tests, crds have been created before creating 'OrganizationRoleTemplate`, it passes everytime on my local machine.

**Comment by nmiculinic** [comment]
> I have no idea why e2e test is complaining about

I'm guessing it takes some time between CRD creation and API server is ready for serving them. I get the same issue locally, though after a retry in few seconds it works fine.

**Comment by jiachengxu** [comment]
> I'm guessing it takes some time between CRD creation and API server is ready for serving them. I get the same issue locally, though after a retry in few seconds it works fine.

Yeah, I see, I can apply these templates manually after a few seconds to wait for API server to be ready, but that is not nice. Do you think this PR is needed? Otherwise, I will just close it and be done with it.

**Comment by nmiculinic** [comment]
well, it's not high on priority list anyway. Maybe it's needed, but from my POV there's bigger fish to fry.

**Pull request closed without merging**
