### PR TITLE
Add goreleaser.

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:
Here is a release that created by this PR: https://github.com/kubermatic/bulward/releases/tag/v0.1.0-DEBUG

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nmiculinic** [comment]
Have you tried running bulward with images pulled from the quay.io repos?

**Comment by jiachengxu** [comment]
> Have you tried running bulward with images pulled from the quay.io repos?

No I haven't,  will try that out

**Comment by jiachengxu** [comment]
@nmiculinic I have tried to pull the images, and they works.

**Pull request merged**
